### PR TITLE
common: Import camera HAL

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by gwolf2u** [comment]
what's this needed for?
OP Cam?

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> what's this needed for?
> OP Cam?

Yes. https://github.com/Hikari-no-Tenshi/android_device_oneplus_guacamoleb-merged/commit/c8462975d722d67173a151d4496530eb9b79303d#diff-92799b87f8aeb1c7fc39949150ba3aa308a48fd5386ac47a2ec9830e2357d7afR30

**Comment by firebird11** [comment]
does the MDM hal need to be updated to ?

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> does the MDM hal need to be updated to ?

I think not needed. New one have same methods.

**Comment by Hikari-no-Tenshi** [comment]
But should me moved to hardware.

**Pull request merged**
